name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: win
            os: windows-latest
            java: 17
          - nickname: macos
            os: macos-latest
            java: 17
          - nickname: linux
            os: ubuntu-latest
            java: 17
    name: CI Build ${{ matrix.nickname }}
    steps:
      - name: Set git config for long paths
        if: runner.os == 'Windows'
        run: |
          git config --system core.longpaths true
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build
        run: ./mvnw -B clean verify
